pipeline {
  agent any
  stages {
    stage('Build Maven Project') {
      steps {
	sh 'mvn -f mavenwebproject/pom.xml clean package'
      }
      post {
	success {
	  echo 'Archiving artifacts'
	  archiveArtifacts artifacts: '**/*.war
	}
      }
    }
    stage('Deploy in Staging Environment') {
      steps {
	build job: 'CodePipeline-CD'
      }
    }
    stage('Deploy to Production Environment') {
      steps {
	timeout(time:2, unit:'DAYS') {
	  input message: 'Approve Production Deployment?'
	}
	build job: 'CodePipeline-Prod'
      }
    }
  }
}
