pipeline {
  agent any
  stages {
    stage('Build Application') {
      steps {
        sh 'mvn -f web-prueba/pom.xml clean package'
      }
      post {
        success {
	  echo "Now archiving the artifacts..."
	  archiveArtifacts artifacts: '**/*.war'
	}
      }
    }
    stage('Deploy to Staging Environment') {
      build job: 'cd-prueba'
    }
  }
}
